### ISSUE TITLE
Miscellaneous Remaining TODO's & Cleanup

### ISSUE THREAD

**Issue by CIS-gvoit** [private-pilot/fitness-model#80]
- [ ] Clean up vestigial fetchCategory calls
- [ ] ​Clean up vestigial fetchCategories calls
- [ ] Clean up CategoryReducer.js
- [ ] Clean up CategoryActions.js
- [ ] Think about how to conditionally render the CategoryTitle / Fitness-level-x.png associated with each Category on "Recommendations"
- [ ] Revisit “scores” API call - not currently working as intended (seems to always return max possible score, instead of the score they should have received if counting only their “yes” answers).
  - [ ] Once this is done, makes it much easier to do conditional rendering per category… if they received the max score for that category, then it shouldn’t be rendered.
  - [ ] Additionally, once this is done, we will have the data we need to start working on displaying a dynamic graph

**Comment by CIS-gvoit** [comment]
Calculate ```maxScore``` and ```receivedScore``` based on data in Redux state ```categories.categories```.
